export type BepField = { id: string; label: string; type?: "text" | "date" | "textarea"; required?: boolean };
export type BepSection = { name: string; lead: string; fields: BepField[] };

const group = (name: string, lead: string, labels: string[]): BepSection => ({
  name,
  lead,
  fields: labels.map((label, index) => ({
    id: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_${index}`,
    label,
    required: true,
    type: /description|definition|strategy|process|responsibilit|brief|requirement|workflow|additional/i.test(label) ? "textarea" : "text",
  })),
});

export const bepSections: BepSection[] = [
  group("Document control", "Controlled issue, revision and approval information.", ["Project name", "Works package / project scope", "BEP document code", "Revision", "Document status", "Issue date", "Prepared by", "Reviewed by", "Approved by"]),
  group("Project information", "General project information used throughout the BEP.", ["Client / Employer", "General contractor", "Project address", "Project number", "Project type", "Project stage", "Project brief", "Project duration", "Location / City", "Main contractor scope"]),
  group("Definitions", "Project-specific ISO 19650 definitions and acronyms.", ["Appointed party definition", "Appointing party definition", "Client definition", "Delivery team definition", "Task team definition", "BIM Execution Plan definition", "Additional project acronyms"]),
  group("Discipline scope", "Detailed discipline, location and delivery scope.", ["Works scope", "Works package", "Architecture scope description", "Structure scope description", "MEP scope description", "BIM deliverables and LOD requirements", "Site access and wider-development context", "Project location / masterplan figure reference"]),
  group("Stakeholders", "Organizations, authorities and project contacts.", ["Client name", "PMC name", "Design consultant name", "Supervision consultant name", "Supervision consultant BIM manager", "General contractor name", "GC BIM manager", "Main contractor name", "Client contact email", "PMC contact email", "Supervision consultant email", "General contractor email", "Main contractor project manager email", "Main contractor BIM lead email"]),
  group("BIM strategy", "Information-management approach and measurable outcomes.", ["BIM goals and objectives", "Common Data Environment", "Information-management standard", "Target level of detail", "Coordination meeting frequency", "Construction clash tolerance", "Project KPIs", "BIM uses and intended outcomes"]),
  group("Requirements", "Exchange Information Requirements and BIM uses.", ["EIR reference code", "Client EIR version and date", "Local authority BIM guideline version", "GC Pre-BEP reference", "Existing conditions modelling requirement", "Site capture requirement", "As-built modelling requirement", "Project information model requirement", "Construction logistics requirement", "Design review requirement", "3D coordination requirement", "4D planning requirement", "5D cost requirement", "Asset information model requirement", "COBie delivery requirement"]),
  group("Milestones", "Information delivery and submission milestones.", ["Manufacturing / construction start", "Manufacturing / construction end", "Handover / as-built start", "Handover / as-built end", "Post-appointment BEP requirement", "Risk register requirement", "MIDP requirement", "MPDT requirement", "RACI matrix requirement", "LOIN requirement", "Clash matrix requirement", "QA/QC checklist requirement", "Asset register requirement", "BIM progress report requirement", "PIM requirement", "O&M information requirement"]),
  group("CDE and federation", "Container breakdown, folder structure and federation strategy.", ["CDE platform", "Work In Progress folder", "Shared folder", "Published folder", "Archive folder", "Main discipline / works container", "Main container description", "Sub-discipline container", "Sub-discipline container description", "Coordination model description", "Federation strategy"]),
  group("Coordinates", "Project coordinates, boundary points and datum.", ["Coordinate framework description", "Boundary point P1 name", "P1 North", "P1 East", "P1 zone / reference", "Boundary point P2 name", "P2 North", "P2 East", "P2 zone / reference", "North / South coordinate", "East / West coordinate", "Elevation / project datum", "Angle to True North", "Shared coordinates", "Additional boundary points"]),
  group("Coordination and QA", "Spatial coordination, tolerances and verification.", ["LOD 400 discipline clash pair", "LOD 400 clash tolerance", "LOD 500 clash rule", "Schematic design tolerance", "Detailed design tolerance", "Tender / IFC tolerance", "Construction tolerance", "BIM progress meeting frequency", "Meeting appointing party", "Meeting PMC", "Meeting supervision consultant", "Meeting general contractor", "Meeting main contractor", "QA/QC review process", "Model verification process", "Information validation authority"]),
  group("Naming", "ISO 19650 container naming and coding conventions.", ["Project number code", "Package number code", "Originator code", "Discipline breakdown code", "Spatial breakdown / level code", "Form / document type code", "Discipline code", "Document number sequence", "GC code", "Client code", "Design consultant code", "Supervision consultant code", "Main contractor code", "All-disciplines package description", "Architecture model description", "Structure model description", "MEP model description"]),
  group("Classification", "Classification, family, material and workset conventions.", ["Project classification standard", "Cost classification standard", "Uniclass system codes", "System code and description", "Product code and description", "Family originator code", "Family discipline code", "Family object code", "Family subtype", "Family manufacturer / generic", "Family descriptor", "Material category", "Material description 01", "Material description 02", "Workset originator", "Workset discipline code", "Workset description"]),
  group("Technology", "Approved software, platforms and hardware.", ["Revit version", "Civil 3D version", "AutoCAD version", "Navisworks version", "Synchro 4D version", "CostX version", "Visualization software", "Document management platform", "Asset management platform", "Site capture technology", "GIS platform", "CPU specification", "GPU specification", "RAM specification", "Storage specification", "Monitor specification", "Network requirement"]),
  group("Responsibilities", "Deliverable ownership across all appointed parties.", ["COBie requirements owner", "COBie production responsible party", "COBie QA/QC approver", "COBie upload responsible party", "COBie final approval", "Pre-appointment BEP owner", "Post-appointment BEP owner", "MIDP owner", "MPDT owner", "LOIN owner", "Clash matrix owner", "QA/QC checklist owner", "Federated model owner", "Coordination report owner", "Asset register owner", "Project information model owner", "Subcontractor responsibilities"]),
  group("Appendices", "Complete appendix register and controlled issue information.", ["Model Breakdown Structure title", "Appendix 01 code", "QA/QC Checklist title", "Appendix 02 code", "Level of Information Need title", "Appendix 03 code", "Title Block Template title", "Appendix 04 code", "Model Production Delivery Plan title", "Appendix 05 code", "Master Information Delivery Plan title", "Appendix 06 code", "Master Clash Detection Matrix title", "Appendix 07 code", "Datum File title", "Appendix 08 code", "Appendix revision", "Appendix issue purpose"]),
];

export const allBepFields = bepSections.flatMap((section) => section.fields);
